### PR TITLE
AStar movement demo based on OpenRPG rewrite

### PR DESCRIPTION
**Pull request by razcore-rad**
Let me know if you find it explained well enough or if there's any problems with it.

- I left in the encounters in as well to server as an example of how objects outside of the TileMap could be used as obstacle with AStar
- included two Robis and one Godette :) just to make it more interesting and to show that this algorithm is generic enough that any number of Party "member" nodes can be used
- made use of the `Events` singleton idea
- also used `_on_signal` single function for catching all signals which are destructured through `match` given the `msg` Dictionary

astar-movement

### CODE REVIEW

**Comment by NathanLovato** [comment]
Before doing a full code and comments review, could you improve some controls?

- The player can't change direction when the characters are moving along a path. Clicking somewhere generates a new path but doesn't update the party's target move position. Same issue with using the keyboard
- Moving the characters with the keyboard doesn't feel great. E.g. if you hold right, add the down key, then release the down key, the characters will stop although the right key is still held.
- Tapping on an event/NPC cell should probably get the party to walk the cell in front of them

**Comment by NathanLovato** [comment]
For the docstrings, may I proof them directly? I can write some general feedback on how you can simplify the style or make them more consistent. Things like avoiding parentheses or shortening some sentences.

The _on_signal method could use some docstring more than any other method. I also don't like it as except for you, the author, and unless you document everything, it's not clear which signal is triggering which bit of code or the expected keys in the message dictionary without browsing through the codebase.

```
func _on_signal(msg: Dictionary = {}, which: String = "") -> void:
```

I'd rather stick to _on_signal_name and one method per signal as it makes the code self documenting and will likely help with debugging and breakpoints.

**Comment by razcore-rad** [comment]
> Before doing a full code and comments review, could you improve some controls?
> 
> * The player can't change direction when the characters are moving along a path. Clicking somewhere generates a new path but doesn't update the party's target move position. Same issue with using the keyboard
> * Moving the characters with the keyboard doesn't feel great. E.g. if you hold right, add the down key, then release the down key, the characters will stop although the right key is still held.
> * Tapping on an event/NPC cell should probably get the party to walk the cell in front of them

Yes, I didn't implement movement "at any time", it instead blocks once it's given a destination.

About the keyboard movement, never crossed my mind to check that case, I'll have to see what's going on there. At the moment I'm handling it via `_unhandled_input` which is also slower compared to `_process` so for it to be immediately responsive, if that's a goal, I need to reimplement it with `_process`.

With `_on_signal`, I'm not convinced either, what I like about is that it's one entry point to all signals and so it keeps everything contained, but on the other hand is as you say very hard to track what is happening so yeah, will go back to one function per signal.

I think it's best if I work on these changes first and then you can work on the comments - sorry I'm used to heavy language from my academic research time :)

**Comment by NathanLovato** [comment]
All good, go ahead :)

**Pull request merged**
