### PR TITLE
Color Palette Plugin

### LINKED ISSUE #20: Add-on: Color palette
## Problem

We're going to have a styleguide with fixed colors, but we don't have a convenient way to assign these colors to icons, bars, text, etc.

This goes for tutorial slideshows made in Godot as well as debug interfaces or tools we might create.

## Color palette

- [ ] Palette widget: should generate a list of buttons from a JSON file.
- [ ] Clicking a button should assign the color to the modulate property of the selected node.
- [ ] The individual buttons/swatches in the palette shouldn't return color objects! The idea is to reuse the components for other tools, e.g. a RichTextLabel editor, where the color will be a string in bbcode tags. Each button should only return a hex color string!
- [ ] The color palette should only be a widget! We should put multiple widgets in a single docker.

_NB: No need to support RGBA values, only hex. Note in Godot the hex format is `AARRGGBB` or `RRGGBB`: alpha comes first._

## Interface

I prepared some UI prototype, see the attached zip : [ColorPalette.zip](https://github.com/GDquest/kickstarter-quest-3/files/2830462/ColorPalette.zip)

One gridcontainer per palette section/category. Keep it this simple: no need for a fluid layout or foldable categories. We're only going to have a handful of swatches to start with, making an elaborate UI would be a waste of time at this point.

Krita's palette docker is a good reference for the layout: simple and efficient.

screenshot from 2019-02-05 11-00-47

```json
"palette_name" : {
    "category_name": [
        "color_uid" : "ffffff",
        "color_uid" : "000000"
    ]
}
```

### PR DESCRIPTION
**Pull request by henriiquecampos**
This hopefully closes #20 I added 2 demo palettes to the commit for reference of the `.json` structure.

[These lines](https://github.com/henriiquecampos/kickstarter-quest-3/commit/9b79dc6f972d71034597029ed5bcc15907943c0d#diff-f153d1b9a739714380946745d8047234R14) can potentially be removed after #21 since it will be the one responsible to manage this

### CODE REVIEW

**Comment by NathanLovato** [comment]
Could you add undo/redo support? I didn't think about mentioning it but every single tool that modifies a node should always support undos. See the UndoRedo object. If you need a hand ask anytime.

**Comment by NathanLovato** [comment]
Also please refactor to make the code follow the styleguide. Mainly:

- Use type hints
- Use onready variables to get nodes only upon initializing the plugin. Having these variables at the top helps to track dependencies in the code, and in general it's a good practice for performances.

**Comment by henriiquecampos** [comment]
Done, I'm just not sure about this line in particular

`onready var _interface: ColorPalette setget , get_interface`

This variable is actually set in `_enter_tree`, I only made it `onready` because it is a dependency of the plugin, and I couldn't find a better way to communicate this dependency. Shall we keep it like this or is better to change it to a simple `var` and add a comment talking about said dependence relation?

**Comment by NathanLovato** [comment]
All good :)

**Pull request merged**
