### PR TITLE
Game juicing demo added

### PR DESCRIPTION
**Pull request by guilhermehto**
There are still some points missing:
- More FX
- Sounds
- Enemy "corpses" 

I'm PRing this as WIP because I'd like to discuss the approach for the toggling of these effects. I tried to avoid using an autoload but this brings some problems. For instance, bullets can have trails - which are particles - the way the toggler is now, we can't toggle these particles on and off because they are instantiated in run time. 

There are two approaches I believe: One is to autoload the toggler and let the nodes check if they should or not activate the particles. The other is to keep using signals and let the toggler know when something spawned and let it turn the particles on/off.

Suggestions on how to handle this are appreciated :)

### CODE REVIEW

**Comment by NathanLovato** [comment]
I'll download and check the project a bit later. Just, when you're done, could you remove all the unused textures from the project? In general they make the PRs a lot harder to review with the code scattered among the .import files

**Comment by NathanLovato** [comment]
Quick review as I have to leave soon, and post the post KS update now:

- Design it for the full screen
- There shouldn't be screenshake when the bullets don't hit an enemy imo
- Bigger bullets
- Auto/rapid fire (and start with low cooldown, then add a button to increase the fire rate)
- Add some spray to the bullets: just a 10 degrees angle. If they're bigger it'll be easier to hit the enemies anyway
- Design it full screen. The focus of this demo should be the game feel and the visuals, for the video. You don't want to work at a low resolution, but rather design the game for 1080p, the recording resolution.

You can code the toggles however you'd like, they're not going to be part of the tutorial anyway. Signals are fine, using a Singleton and having a built-in script on each and every button is fine.

I have to experiment to see what would work best. You can always toggle something: regarding particles, you can assign them to a node group and call queue_free() or set the visibility to false on all nodes in the group upon toggling a button off.

If you have any more questions I'll be there to answer tomorrow.

**Comment by guilhermehto** [comment]
Done @NathanLovato  :)

**Comment by NathanLovato** [comment]
I pulled the latest changes, made sure to reset my changes and half of the buttons don't do work. Rapid fire, spray, weak enemies don't work here. Can you fix that?

Be sure to make the game full-screen (and to make it look good when it's full-screen) before you record, as I told you above.

**Comment by guilhermehto** [comment]
I pulled the PR in another branch and everything was working, I only found a few bugs when restarting the game that I fixed in the last commit. 

Can you test it again please?

**Pull request merged**
